<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$objRequest = $om->get('Magento\Framework\App\RequestInterface');
if($objRequest->getParam('idproof'))
{
    ?>
    <script type="text/javascript">
        requirejs(['jquery'], function(jQuery){
            jQuery(function(){
                window.setTimeout('fnLoadIdentityProofTab()',5000);
            });
        });
        function fnLoadIdentityProofTab()
        {
            jQuery('#tab_block_custom_registration_edit_tab_view').trigger("click");
        }
    </script>
    <?php
}
?>