<?php
/**
 * Commission template for separate item
 *
 */

/**
 * @var $this Cibilia\Commission\Block\View
 * @see Cibilia\Commission\Block\View
 */
?>
<?php $_commissionItem = $this->getCommission(); ?>
    <div class="commission_item_subtitle">
        <?php echo $this->formatDate($_commissionItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_commissionItem->getAuthor()) ?>
    </div>

<div class="commission_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_commissionItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_commissionItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="commission_item_content"><?php echo $_commissionItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>