<?php $_commission = $this->getCollection(); ?>
<?php if ($_commission->getSize()): ?>
<div class="commission_list_view">
    <?php foreach ($_commission as $commissionItem): ?>
        <div id="item_<?php echo $commissionItem->getId() ?>" class="commission_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($commissionItem) ?>">
                    <?php echo $this->escapeHtml($commissionItem->getTitle()) ?>
                </a>
            </h2>

            <div class="commission_item_subtitle">
                <?php echo $this->formatDate($commissionItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($commissionItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($commissionItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($commissionItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Commission.'); ?></span></div>
<?php endif ?>
