<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder(); ?>
<?php $vendorId = $block->getVendor(); ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-qty">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-price">
                    <?= /* @escapeNotVerified */  __('Price'); ?>
                </th>
            </tr>
        </thead>
        <?php $vendorTotal = 0; ?>
        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
                $ObjProduct = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getProductId());
                
                if($ObjProduct->getUdropshipVendor() != $vendorId){
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
                <?php $vendorTotal = $vendorTotal + $_item->getRowTotalInclTax(); ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <tr class="<?php /* @escapeNotVerified */ echo __('grand_total')?>">
                <th scope="row" colspan="2">
                    <strong><?php echo __('Total Amount');?></strong>
                </th>
                <td>
                    <strong><?php /* @escapeNotVerified */ echo $objectManager->create('Magento\Framework\Pricing\Helper\Data')->currency($vendorTotal,true,false); ?></strong>
                </td>
            </tr>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
