<?php $this->helper('Cibilia\Summary\Helper\Customer')->redirectIfNotLoggedIn();?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $customerSession = $objectManager->get('Magento\Customer\Model\Session'); ?>
<?php $objCustomer = $objectManager->create('Magento\Customer\Model\Customer')->load($customerSession->getCustomer()->getId()); ?>
<?php if ($objCustomer && $objCustomer->getId()): ?>
   
<?php $strDefaultPaytype = 1; 
  if($objCustomer->getDefaultPayoutType()){
    $strDefaultPaytype = $objCustomer->getDefaultPayoutType();
  }
?>
<form class="form-address-edit" id="default-payout-form" method="POST" action="<?php echo $this->getUrl('summary/index/payoutpost'); ?>">
   <div id="tab2" class="tab-pane">
      <div class="form-group">
         <div class="col-md-2 left-label">
            <a class="radio-control paypalControl <?php echo ($strDefaultPaytype == 2) ? 'active' : '';?>" id="paypalControl"></a>
         </div>
         <div class="col-md-9 main-bg">
            <fieldset class="fieldset">
               <div class="field name required">
                  <label class="label" for="paypal_email"><span><?php echo __('Paypal') ?></span></label>
                  <div class="control">
                     <input name="paypal_email" type="text" id="paypal_email" placeholder="<?php echo __('Paypal Email') ?>" title="<?php echo __('Paypal') ?>" value="<?php echo $objCustomer->getPayoutPaypalEmail(); ?>" class="input-text" />
                     <span style="display:none;" class="span-error paypal-required"><?php echo __('This is a required field.') ?></span>
                     <span style="display:none;" class="span-error paypal-email"><?php echo __('Please enter a valid email address.') ?></span>
                  </div>
               </div>
            </fieldset>
         </div>
         <div style="clear:both"></div>
      </div>
      <div class="form-group">
         <div class="divide-payment">
            <span>- Or -</span>
         </div>
         <div style="clear:both"></div>
      </div>
      <div class="form-group">
         <div class="col-md-2 left-label">
            <a class="radio-control bankControl <?php echo ($strDefaultPaytype == 1) ? 'active' : '';?>" id="bankControl"></a>
         </div>
         <div class="col-md-9 detail-block main-bg">
            <fieldset class="fieldset">
               <div class="field required">
                  <label class="label" for="payout_bank_detail"><span><?php echo __('Bank Transfer') ?></span></label>
                  <div class="control">
                     <textarea name="payout_bank_detail" id="payout_bank_detail" title="<?php echo __('Bank Transfer') ?>" placeholder="<?php echo __('Bank Details') ?>" class="textarea required-entry" ><?php echo $objCustomer->getPayoutBankDetails(); ?></textarea>
                     <span style="display:none;" class="span-error bank-required"><?php echo __('This is a required field.') ?></span>
                  </div>
               </div>
            </fieldset>
         </div>
         <div style="clear:both"></div>
      </div>
      <input type="hidden" name="paytype" id="paytype" value="<?php echo $strDefaultPaytype; ?>" />
      <input type="hidden" name="custid" id="custid" value="<?php echo $objCustomer->getId(); ?>" />
   </div>
   <div style="clear:both"></div>
   <div class="actions-toolbar col-md-9">
      <div class="primary">
         <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>">
         <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
         </button>
      </div>
   </div>
</form>


    <style type="text/css">
    .span-error{
  color: #e02b27;
  font-size: 1.2rem;
  margin-top: 7px;
}
.actions-toolbar .primary {
  float: none;
}
.actions-toolbar .primary .action {
  margin: 0;
}
    .actions-toolbar.col-md-9 {
  width: 47%;
}
    .actions-toolbar {
  text-align: right;
}
    .divide-payment > span {
  color: #bbb;
  font-size: 22px;
}
    .col-md-2 {
  width: 10%;
}
.main-bg {
  background: #f5f5f5 none repeat scroll 0 0;
  padding: 20px 30px;
}
.col-md-9 {
  width: 70%;
}
.col-md-12 {
  width: 100%;
}
.col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9 {
  float: left;
}
.form-horizontal .form-group {
    margin-left: -15px;
    margin-right: -15px;
}
.form-group {
    margin-bottom: 15px;
}
.col-md-3 {
  width: 25%;
}
.divide-payment {
  margin: 5px 0;
  text-align: center;
  width: 47%;
}
.radio-control.active {
  background: rgba(0, 0, 0, 0) url("<?php echo $block->getViewFileUrl('images/custom-ora.png');?>") no-repeat scroll 0 0;
}
.radio-control {
  background: rgba(0, 0, 0, 0) url("<?php echo $block->getViewFileUrl('images/custom-ora.png');?>") no-repeat scroll 0 -22px;
  display: inline-block;
  height: 22px;
  width: 25px;
  cursor: pointer;
}
.left-label {
  line-height: 100px;
  text-align: center;
}
.paypal-img img {
  width: 120px;
}
    </style>
    <script type="text/javascript">
    requirejs(['jquery'], function ($) {
        jQuery(document).ready(function($) {
             jQuery('.paypalControl').click(function(event) {
                event.preventDefault();
                if (!jQuery(this).hasClass('active')) {
                    jQuery(this).addClass('active')
                }
                jQuery('#paytype').val(2);
                jQuery('.bankControl').removeClass('active');
            });
            jQuery('.bankControl').click(function(event) {
                event.preventDefault();
                if (!jQuery(this).hasClass('active')) {
                    jQuery(this).addClass('active')
                }
                jQuery('#paytype').val(1);
                jQuery('.paypalControl').removeClass('active');
            });

            jQuery( "#default-payout-form" ).submit(function( event ) {
             jQuery('.paypal-required').hide();
              jQuery('.paypal-email').hide();
              jQuery('.bank-required').hide();
              
              var payType = jQuery('#paytype').val();
              if(payType == '2'){
                if(jQuery('#paypal_email').val() == ''){
                    jQuery('.paypal-required').show();
                    return false;
                }
                if(!validateEmail(jQuery('#paypal_email').val())) {
                    jQuery('.paypal-email').show();
                    return false;
                }
              }
              if(payType == '1'){
                if(jQuery('#payout_bank_detail').val() == ''){
                    jQuery('.bank-required').show();
                    return false;
                }
              }

            });
            function validateEmail(sEmail) {
                var filter = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;
                if (filter.test(sEmail)) {
                    return true;
                } else {
                    return false;
                }
            }
        });
    });
    </script>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Default Payout.'); ?></span></div>
<?php endif ?>
