<?php $this->helper('Cibilia\Summary\Helper\Customer')->redirectIfNotLoggedIn();?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $customerSession = $objectManager->get('Magento\Customer\Model\Session'); ?>
<?php 
    $objSummary = $objectManager->create('Cibilia\Summary\Model\Summary')->load($customerSession->getCustomer()->getId(),'cibilian_id');
    $requestedAmount = 0;
    $earnedAmount = 0;
    $pendingAmount = 0;

    if($objSummary && $objSummary->getId()){
        $earnedAmount = $objSummary->getTotalAmount();
        $arrRequestedCollection = $objectManager->create('Cibilia\Redemption\Model\Redemption')->getCollection()->addFieldToFilter('cibilian_id',$objSummary->getCibilianId())->addFieldToFilter('status',2);
        foreach ($arrRequestedCollection as $withdraw) {
           $requestedAmount = $requestedAmount + $withdraw->getAmount();
        }
        $pendingAmount = $objSummary->getPendingAmount() - $requestedAmount;

    }
    $lockedAmount = 0;
        
    $arrLockedCollection = $objectManager->create('Cibilia\Commission\Model\Commissions')->getCollection()->addFieldToFilter('cibilian_id',$customerSession->getCustomer()->getId())->addFieldToFilter('status',3);
    foreach ($arrLockedCollection as $locked) {
       $lockedAmount = $lockedAmount + $locked->getTotalCommission();
    }

    $arrTotalVendorOrders = $objectManager->create('Cibilia\Commission\Model\Commissions')->getCollection()->addFieldToFilter('cibilian_id',$customerSession->getCustomer()->getId());
?>
    <div class="summary_list_view">
        <?php //foreach ($_summary as $summaryItem): ?>
            <div id="item_<?php echo $objSummary->getId() ?>" class="summary_list_item">
                <ul>
                    <li>
                        <span><?php echo __('Total Commission Earned: '); ?><span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($earnedAmount,true,false);?></span></span>
                        <?php if(intval($earnedAmount) > 0){?>
                        <span><a href="<?php echo $block->getUrl('commission/index') ?>"><?php echo __('Commission Earned List'); ?></a></span>
                        <?php } ?>
                    </li>
                    <li>
                        <span><?php echo __('Total Commission Locked: '); ?><span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($lockedAmount,true,false);?></span></span>
                        <?php if(intval($lockedAmount) > 0){?>
                            <span><a href="<?php echo $block->getUrl('commission/index/locked') ?>"><?php echo __('Commission Locked List'); ?></a></span>
                        <?php } ?>
                        
                    </li>
                    <li>
                        <span><?php echo __('Total Commission Received: '); ?><span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($objSummary->getPaidAmount(),true,false);?></span></span>
                        <?php if(intval($objSummary->getPaidAmount()) > 0){?>
                        <span><a href="<?php echo $block->getUrl('redemption/index/paid') ?>"><?php echo __('Commission Received List'); ?></a></span>
                        <?php } ?>
                    
                    </li>
                    <li>
                        <span><?php echo __('Total Commission Pending: '); ?><span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($pendingAmount,true,false);?></span></span>
                         <?php if(intval($pendingAmount) > 0){?>
                        <span><a href="<?php echo $block->getUrl('redemption/index/withdraw') ?>"><?php echo __('Withdraw Commission'); ?></a></span>
                        <?php } ?>
                    </li>
                    <?php if($objSummary->getId() && count($arrRequestedCollection) > 0){ ?>
                    <li>
                        <span><?php echo __('Total Requested Amount: '); ?><span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($requestedAmount,true,false);?></span></span>
                            <span><a href="<?php echo $block->getUrl('redemption/index/requested') ?>"><?php echo __('Requested Withdrawl List'); ?></a></span>
                    </li>
                    <?php } ?>
                    <?php if(count($arrTotalVendorOrders) > 0){ ?>
                    <li>
                        <span><?php echo __('Total Number of Orders: '); ?><span class="price"><?php echo count($arrTotalVendorOrders);?></span></span>
                            <span><a href="<?php echo $block->getUrl('commission/index/orders') ?>"><?php echo __('View All Orders'); ?></a></span>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        <?php //endforeach; ?>
    </div>
    <style type="text/css">
    .summary_list_item li {
      font-size: 18px;
      list-style: outside none none;
    }
    .summary_list_item li .price {
  margin-left: 5px;
  margin-right: 15px;
  font-weight: bold;
}
.summary_list_item ul {
  padding: 0;
}
    </style>

