<?php $this->helper('Cibilia\Commission\Helper\Customer')->redirectIfNotLoggedIn();?>
<?php $arrRequestedWithdrawl = $this->getCollection(); ?>
<?php if ($arrRequestedWithdrawl->getSize()): ?>
    <?php $arrWithdrawlTypes = array('1'=>'Bank Transfer','2'=>'Paypal'); ?>
    <?php $arrWithdrawlStatus = array('1'=>'Paid','2'=>'Unpaid','3'=>'Cancled'); ?>
<div class="requested_list_view">
    <?php ///foreach ($_commission as $commissionItem): ?>
        <div class="table-wrapper orders-history">
            <table class="data table table-order-items history" id="request-withdrawl-list">
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Paid Withdrawl List') ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Id#') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Order#') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Amount') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('WithdrawlType') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Paypal/BankDetails') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Comments') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('TransactionId') ?></th>
                        <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                        <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('CreatedAt') ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($arrRequestedWithdrawl as $withdrawl): ?>
                        <tr>
                            <td data-th="<?php echo $block->escapeHtml(__('Id #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $withdrawl->getData("redemption_id"); ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $withdrawl->getData("order_id"); ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Amount')) ?>" class="col shipping"><?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($withdrawl->getData("amount"),true,false); ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Withdrawl Type')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $arrWithdrawlTypes[$withdrawl->getData("withdrawal_type")]; ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Paypal/Bank Details')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $withdrawl->getData("email_bank_details"); ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Comments')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $withdrawl->getData("comment"); ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Transaction Id')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $withdrawl->getData("transaction_id"); ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $arrWithdrawlStatus[$withdrawl->getData("status")]; ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Created At')) ?>" class="col total"><?php /* @escapeNotVerified */ echo date("M d, Y, h:i:s",strtotime($withdrawl->getData("created_at")));?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
    </div>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Requested Withdrawl.'); ?></span></div>
<?php endif ?>
