<div class="custom-page-link">
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="<?php echo $block->getBaseUrl(); ?>our-manifesto"><?php echo __('our manifesto'); ?></a>
        </li>
        <li class="list-inline-item">
            <a href="<?php echo $block->getBaseUrl(); ?>how-cibilia-works"><?php echo __('how cibilia works'); ?></a>
        </li>
    </ul>
</div>