<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions">
    <?php  $_order = $block->getOrder() ?>
    <a class="action print"
       href="<?php /* @escapeNotVerified */ echo $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?php /* @escapeNotVerified */ echo __('Print Order') ?></span>
    </a>
    <?php echo $block->getChildHtml(); ?>
</div>
