<?php $_cibiliancommission = $this->getCollection(); ?>
<?php if ($_cibiliancommission->getSize()): ?>
<div class="cibiliancommission_list_view">
    <?php foreach ($_cibiliancommission as $cibiliancommissionItem): ?>
        <div id="item_<?php echo $cibiliancommissionItem->getId() ?>" class="cibiliancommission_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($cibiliancommissionItem) ?>">
                    <?php echo $this->escapeHtml($cibiliancommissionItem->getTitle()) ?>
                </a>
            </h2>

            <div class="cibiliancommission_item_subtitle">
                <?php echo $this->formatDate($cibiliancommissionItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($cibiliancommissionItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($cibiliancommissionItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($cibiliancommissionItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no CibilianCommission.'); ?></span></div>
<?php endif ?>
