<?php
/**
 * CibilianCommission template for separate item
 *
 */

/**
 * @var $this Cibilia\CibilianCommission\Block\View
 * @see Cibilia\CibilianCommission\Block\View
 */
?>
<?php $_cibiliancommissionItem = $this->getCibilianCommission(); ?>
    <div class="cibiliancommission_item_subtitle">
        <?php echo $this->formatDate($_cibiliancommissionItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_cibiliancommissionItem->getAuthor()) ?>
    </div>

<div class="cibiliancommission_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_cibiliancommissionItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_cibiliancommissionItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="cibiliancommission_item_content"><?php echo $_cibiliancommissionItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>