<?php
/**
 * Redemption template for separate item
 *
 */

/**
 * @var $this Cibilia\Redemption\Block\View
 * @see Cibilia\Redemption\Block\View
 */
?>
<?php $_redemptionItem = $this->getRedemption(); ?>
    <div class="redemption_item_subtitle">
        <?php echo $this->formatDate($_redemptionItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_redemptionItem->getAuthor()) ?>
    </div>

<div class="redemption_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_redemptionItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_redemptionItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="redemption_item_content"><?php echo $_redemptionItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>