<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomRegistration
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script>
	require([
            'jquery',
            "mage/mage",
        ], function($){
    	var alerttext = '';
         $("#save_custom_fields").on( "click", function() {
         	 $.ajax('<?php echo $block->getAjaxCheckUrl() ?>', {
         	 	method: 'post',
         	 	data:$('#custom_form').serialize(),
                onSuccess: function(transport){

                }
         	 });
         });       
    });
</script> 
