<?php $this->helper('Cibilia\Cibilians\Helper\Customer')->redirectIfNotLoggedIn();?>
<fieldset class="fieldset">
	<div class="actions-toolbar">
		<div class="primary">
			<a href="<?php echo $this->getUrl('cibilians/advertisers/edit'); ?>"<button type="submit" title="<?php echo __('Add Advertiser') ?>" class="action submit primary">
				<span><?php echo __('Add Advertiser - Referral 1') ?></span>
			</button></a>
			<a href="<?php echo $this->getUrl('cibilians/advertisers/editp'); ?>"<button type="submit" title="<?php echo __('Add Advertiser') ?>" class="action submit primary">
				<span><?php echo __('Add Advertiser - Referral 2') ?></span>
			</button></a>
		</div>
	</div>
</fieldset>
<?php $_orders = $block->getOrders(); ?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Vendor #') ?></th>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Registered date') ?></th>
                    <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Company name') ?></th>
                    <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Email') ?></th>
                    <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Mobile') ?></th>
                    <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getData("reg_id"); ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getData('registered_at')) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $_order->getData("vendor_name"); ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->getData("email");?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->getData("telephone");?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo "Pending"; ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have not referred any advertisers'); ?></span></div>
<?php endif ?>
