<?php $this->helper('Cibilia\Cibilians\Helper\Customer')->redirectIfNotLoggedIn();?>
<form class="form-address-edit" method="POST" action="<?php echo $this->getUrl('cibilians/advertisers/recommend'); ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'> 
  <?php $params = $block->getRequest()->getParams();?>
 <fieldset class="fieldset">
        
        <div class="field required">
            <label class="label" for="recommendation"><span><?php echo __('Enter your recommendation') ?></span></label>
            <div class="control">
                <textarea name="recommendation" id="recommendation" data-validate="{required:true}"></textarea>
            </div>
        </div>
         <input name="vendor_id" type="hidden" value="<?php echo $params['vendor_id'];?>"/>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
	
    </fieldset>
</form>