<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomRegistration
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
    $data = $block->getModel();
    $fileSignal = 0;
    $booleanSignal = 0;
    $textSignal = 0;
    $codeSignal = 0;
    $textareaSignal = 0;
    $dependableTextareaSignal = 0;
    $selectSignal = 0;
    $dependableSignal=0;
    $dependableSelectoptionSignal = 0;
    $dependableAllowedExtensionsSignal = 0;
    $dependableBoolean=0;
    $fileExtensionValue='';
    $defaultExtensionValue='';
    $dependableFrontendInput='';
    $selectoption='';
    $dependableAllowedExtensions='';
    if($data->getFrontendInput() == "image"){
    	 
        $fileSignal = 1;
        $fileExtensionValue = $data->getNote();
        $defaultExtensionValue='jpg,png,gif';
    }
    if($data->getFrontendInput() == "file"){
        $fileSignal = 1;
        $fileExtensionValue = $data->getNote();
        $defaultExtensionValue='pdf,zip,doc';
    }
    if($data->getFrontendInput() == "text"){
        $textSignal = 1;
    }
    if($data->getFrontendInput() == "boolean"){
        $booleanSignal = 1;
    }
    if($data->getAttributeId()){
        $codeSignal = 1;
    }
    if($data->getFrontendInput() == "textarea"){
        $textareaSignal = 1;
    }
    if($data->getFrontendInput() == "select" || $data->getFrontendInput() == "multiselect"){
        $selectSignal = 1;
        $options = $data->getSource()->getAllOptions();
        foreach ($options as $key => $value) {
            if ($value['value'] != '')
                $selectoption .=$value['label'].',';
        }
    }
    $isRequiredArray = explode(' ', $data->getFrontendClass());
    if(in_array('dependable_field_'.$data->getAttributeCode(), $isRequiredArray)){

        $dependableData = $block->getDependableModel();
        $dependableSignal = 1;
        $dependableFrontendInput = 'dependable_'.$dependableData->getFrontendInput();
        if($dependableFrontendInput == "dependable_select" || $dependableFrontendInput == "dependable_multiselect"){
            $dependableSelectoptionSignal = 1;
        }
        if($dependableFrontendInput == "dependable_file"){
            $defaultExtensionValue='jpg,png,gif';
            $dependableAllowedExtensions = $dependableData->getNote();
            $dependableAllowedExtensionsSignal = 1;
        }
        if($dependableFrontendInput == "dependable_image"){
            $dependableAllowedExtensions = $dependableData->getNote();
            $dependableAllowedExtensionsSignal = 1;
            $defaultExtensionValue='pdf,zip,doc';
        }
        if($dependableFrontendInput == "dependable_boolean"){
            $dependableBoolean = 1;   
        }
    }
?>

<script id="allowed_extension_template" type="text/x-magento-template">
    <div class="admin__field field field-allowed_extensions  required _required allowed_extensions_type_container" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-form-field-allowed_extensions">
        <label class="label admin__field-label" for="allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-input-name-label"><span><?php echo __('Allowed Extension') ?></span></label>
        <div class="admin__field-control control">
            <input id="customfields_allowed_extensions" name="allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-allowed-extensions" value="<?php echo $fileExtensionValue; ?>" title="<?php echo __('Allowed Extension') ?>" type="text" class=" input-text admin__control-text required-entry _required" aria-required="true">
            <?php if ($defaultExtensionValue != ''): ?>
            <comment>eg:<?php echo $defaultExtensionValue; ?></comment>
            <?php else: ?>
             <comment>eg:<%- data.allowedextension %></comment>
            <?php endif; ?>
        </div>
    </div>
</script>
<script id="dependable_allowed_extension_template" type="text/x-magento-template">
    <div class="admin__field field field-dependable-allowed-extensions  required _required dependable_allowed_extensions_type_container" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-form-field-dependableAllowedExtensions">
        <label class="label admin__field-label" for="allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-input-name-label"><span><?php echo __('Dependable Allowed Extension') ?></span></label>
        <div class="admin__field-control control">
            <input id="customfields_allowed_extensions" name="dependableAllowedExtensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-dependable-allowed-extensions" value="<?php echo $dependableAllowedExtensions; ?>" title="<?php echo __('Dependable Allowed Extension') ?>" type="text" class=" input-text admin__control-text required-entry _required" aria-required="true">
            <?php if ($defaultExtensionValue != ''): ?>
            <comment>eg:<?php echo $defaultExtensionValue; ?></comment>
            <?php else: ?>
             <comment>eg:<%- data.dependExtension %></comment>
             <?php endif; ?>
        </div>
         
    </div>
</script>
<?php
        $optionData = [
        'fileSignal'                    => $fileSignal,
        'textSignal'                    => $textSignal,
        'codeSignal'                    => $codeSignal,
        'textareaSignal'                => $textareaSignal,
        'dependableTextareaSignal'      => $dependableTextareaSignal,
        'dependableSignal'              => $dependableSignal,
        'selectSignal'                  => $selectSignal,
        'dependableSelectoptionSignal'  => $dependableSelectoptionSignal,
        'dependableAllowedAxtensionsSignal' => $dependableAllowedExtensionsSignal,
        'fileExtensionValue'                => $fileExtensionValue,
        'dependableExtnValue'           => $dependableAllowedExtensions,
        'booleanSignal'                 => $booleanSignal,
        'defaultExtensionValue'         => $defaultExtensionValue,
        'dependableBoolean'             => $dependableBoolean
    ];
    $serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($optionData);
    ?>
<script type="text/x-magento-init">
{
    "*": {
        "customDependableField": <?php /* @noEscape */ echo $serializedData; ?>
    }
}
</script>
