<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if($block->getAvailableRedeem()) :?>
<div class="cart-redeem">
<div class="block redeem" id="block-redeem">
    <div class="title" data-role="title">
        <strong id="block-redeem-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Redeem Your Commisiion') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-redeem-heading">
        <form id="redeem-amount-form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('redemption/index/redeem') ?>"
              method="post"
              data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}' >
              <div class="total-redeen-lable">
                <label for="total-commission" class="label">
                  <span><?php /* @escapeNotVerified */ echo __('Total Availaibe Commission: ') ?></span>
                  <span class="redeem-amount"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($block->getAvailableRedeem(),true,false);?></span>
                </label>
              </div>
            <div class="fieldset redeem<?php echo($block->getRedeemAmount()) ? ' applied' : ''?>">
                <input type="hidden" name="remove_redeem" id="remove_redeem" value="0" />
                <input type="hidden" id="avail-amount" value="<?php echo $block->getAvailableRedeem();?>"/>
                <div class="field">
                    <label for="redem_amount" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter redeem amount') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="redem_amount" name="redem_amount" value="<?php echo($block->getRedeemAmount()) ? $block->getRedeemAmount() : ''; ?>" placeholder="<?php echo $block->escapeHtml(__('Enter Redeem Amount'));?>" data-validate="{required:true,number:true}" />
                    </div>
                        <span style="display:none;" class="span-error withdraw-error"><?php echo __('Amount is more than available.') ?></span>
                        <span style="display:none;" class="span-error withdraw-amount-digit"><?php echo __('Please enter valid amount.') ?></span>
                    
                </div>
                <div class="actions-toolbar">
                    <div class="primary" style="margin-right:15px;">
                        <button type="submit" value="<?php /* @escapeNotVerified */ echo __('Apply Redeem') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Apply Redeem') ?></span>
                        </button>
                    </div>
                    <?php if($block->getRedeemAmount()): ?>
                        <div class="primary">
                            <button  type="button" id="cancel_redeem" value="<?php /* @escapeNotVerified */ echo __('Cancel Redeem') ?>"><span><?php /* @escapeNotVerified */ echo __('Cancel Redeem') ?></span></button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<style type="text/css">
.cart-redeem {
  border: 0 none;
  box-sizing: border-box;
  clear: left;
  float: left;
  margin-bottom: 25px;
  margin-top: 25px;
  order: 1;
  padding-right: 4%;
  width: 48%;
}
.redeem-amount{
font-weight: 700;
color: #666666;
font-size: 1.8rem;
line-height: 1;
white-space: nowrap;
}
.span-error{
          color: #e02b27;
          font-size: 1.2rem;
          margin-top: 7px;
        }
.cart-redeem .block > .title strong {
  color: #1979c3;
  font-weight: 400;
  font-size: 1.6rem;
}
/*.redeem .input-text {
  width: 276px;
}
*/.redeem .actions-toolbar {
  display: table-cell;
  vertical-align: top;
}
.redeem .field {
  display: table-cell;
}
.fieldset.redeem {
  display: table;
  width: 100%;
}
.cart-redeem .fieldset > .field > .label {
  display: none;
}
.total-redeen-lable .label {
  display: block;
  font-size: 16px;
  margin-bottom: 10px;
}
</style>
<script type="text/javascript">
    requirejs(['jquery'], function ($) {
        jQuery(document).ready(function($) {
            jQuery( "#redeem-amount-form" ).submit(function( event ) {
            
                
                jQuery('.withdraw-error').hide();
                jQuery('.withdraw-amount-digit').hide();
                  

                var isCancel = jQuery('#remove_redeem').val();
                if(!isCancel){
                  
                  var withdrawlAmount = jQuery('#redem_amount').val();
                  var availAmount =  parseInt(jQuery('#avail-amount').val());

                  if(allnumeric(withdrawlAmount)) {
                      if(withdrawlAmount > availAmount){
                          jQuery('.withdraw-error').show();
                          return false;
                      }
                  }
                  if(withdrawlAmount <= 0) {
                      return false;
                  }  
                }
            });
            jQuery('#cancel_redeem').bind('click',function(event) {
                jQuery('#remove_redeem').val(1);
                jQuery( "#redeem-amount-form" ).submit();
            });
            
            function allnumeric(inputtxt){
              var numbers = /^[0-9]+$/;  
              if(inputtxt.match(numbers))  
              {
                return true;  
              }else{  
                return false;  
              }  
           }  
        });
    });
    </script>
<?php else:?>
<style type="text/css">
  .totals.redeem{
  display: none;
}
</style>
<?php endif; ?>