<?php
    $helper =   $this->helper('StageBit\CustomCode\Helper\Data');
    $url    =   $block->getBaseUrl();
    list($detail,$isVisible) = $block->getWebsitesData();

    if($isVisible){
?>

<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'bootstrapMin',
        'bootstrapSelect'
    ], function ($) {       
        //$(".siteSwitch").customswitch();
		$(document).ready(function() {
            $('select.siteSwitch').selectpicker({
                caretIcon: ''
            });

            $(document.body).on("change",".siteSwitch",function(){

                var $option = $(this).find('option:selected');

                var value = $option.val();

                window.location.href = value;
            });
   			return false;

        });
    });
</script>

<select name="country" class="siteSwitch">

<?php foreach($detail as $key => $value): ?>
	<option data-thumbnail= "<?php echo $helper->getMediaUrl().'flags/'.$value['code'].'.svg' ?>"  value= "<?php echo $value['url']; ?>" class="selectedSite" <?php echo  $url == $value['url'] ? 'selected' : ''; ?>><?php echo $value['name'] ?></option>
<?php endforeach; ?>

</select>
<?php
	}
?>
