<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomRegistration
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
if ($block->getConfigData('enable_registration')) {
	$condition = $block->getConditionData();
	?>
	<?php echo $block->getChildHtml('style_template'); ?>
	<div class="field choice privacy-container">
		<div class="checkbox-container">
			<input type="checkbox"
					id="<?php echo $block->getNameInLayout(); ?>"
					name="<?php echo $block->getNameInLayout(); ?>"
					value="0"
					onchange="this.value = this.checked ? 1 : 0;"
					title="<?php echo $block->escapeHtml($block->getConfigData('checkbox_text')) ?>"
					class="checkbox"
					data-validate="{required:true}"/>
				<label for="<?php echo $block->getNameInLayout(); ?>">
						<span>
							<a id="read-term-condition" href="#" class="clearer news-term-condition"><?php echo __('Terms & Conditions '); ?></a>
							<?php echo __('and'); ?>
							<a id="read-privacy" href="#" class="clearer read-privacy"><?php echo __(' Privacy & Cookie Policy'); ?></a>
						</span>
				</label>
		</div>
	</div>
	<script type="text/x-magento-init">
	{
	    "*": {
	        "termAndCondition": <?php echo $block->getConditionContent(); ?>
	    }
	}
	</script>
<?php } ?>