<?php //$this->helper('Cibilia\Cibilians\Helper\Customer')->redirectIfNotLoggedIn();?>
<?php $vid = base64_decode($this->getRequest()->getParam('id'));
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $objVendor = $objectManager->create('\Unirgy\Dropship\Model\Vendor')->load($vid);
?>
<?php if($objVendor && $objVendor->getId()) { ?>
    
    <?php $isType = $objectManager->create('\Cibilia\Idproofs\Model\Idproof')->getIsSelectType($objVendor->getId()); ?>
    <?php if($isType){ ?>
       <h4><?php echo __('Vendor Type had already been selected.') ?></h4>
    <?php } else{ ?>
        <?php $arrVendortype = $block->getVendortype(); ?>
        <form class="form-address-edit" method="POST" action="<?php echo $this->getUrl('idproofs/index/vendortype',array('id' => $vid)); ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
            
            <div class="vendor-type-box">
                <fieldset class="fieldset">
                    <div class="field name required">
                        <label class="label" for="vendor_type"><span><?php echo __('Select your type') ?></span></label>
                        <div class="control">
                            <?php if(count($arrVendortype) > 0){ ?>
                                <?php foreach ($arrVendortype as $key => $value) { ?>
                                    <?php if($value['value'] == 0){
                                        continue;
                                    }?>
                                    <input type="radio" data-validate="{required:true}" name="vendor_type" value="<?php echo $value['value']; ?>"><?php echo $value['label'];?><br>
                                <?php } ?>
                                        
                            <?php } ?>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save Info') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Save Info') ?></span>
                    </button>
                </div>
            </div>
            
        </form>
        <style type="text/css">
        .vendor-type-box {
          display: inline-block;
          width: 100%;
          margin-bottom: 20px;
        }
        </style>
    <?php }?>
    
<?php }else{ ?>
    <h4><?php echo __('No Vendor Found') ?></h4>
<?php } ?>
