<?php
// @codingStandardsIgnoreFile
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>

    <table cellspacing="0" cellpadding="0" border="0" width="650">
        <thead>
        <tr>
            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Additional Information:</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">
                <table cellspacing="0" class="form-list">
                     <?php
                        $orderHelper = $this->helper('Webkul\CustomRegistration\Helper\Order');
                        $attributeCollection = $orderHelper->attributeCollectionFilter(); ?>
                        <?php $_customerData = $orderHelper->getCurrentCustomer($_order->getCustomerId())->toArray(); ?>
                        <?php foreach ($attributeCollection as $attributeData):?>
                            <?php $attrAsArray = $attributeData->toArray(); ?>
                            <?php $_fieldValue = '';
                                $optionLabel = [];
                                foreach ($_customerData as $key => $value) {
                                    if($attrAsArray['attribute_code'] == $key){
                                        if ($attrAsArray['frontend_input'] == 'date') {
                                            $_fieldValue = $this->formatDate($value, \IntlDateFormatter::SHORT, false);
                                        } elseif ($attrAsArray['frontend_input'] == 'boolean') {
                                            $_fieldValue = $value;
                                        } elseif ($attrAsArray['frontend_input'] == 'select') {
                                            foreach ($attributeData->getSource()->getAllOptions() as $instance) {
                                                if ($value == $instance['value']) {
                                                    $_fieldValue = $instance['label'];
                                                }
                                            }
                                        } elseif ($attrAsArray['frontend_input'] == 'multiselect') {
                                            foreach ($attributeData->getSource()->getAllOptions() as $instance) {
                                                
                                                if (in_array($instance['value'], $value)) {
                                                    $optionLabel[] = $instance['label'];
                                                }
                                            }
                                            $_fieldValue = implode(',', $optionLabel);
                                        } elseif ($attrAsArray['frontend_input'] == 'image') {
                                            $_fieldValue = "<img class='wk_images' width='75' height='75' alt='image' src='".$this->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'pub/media/customfield/image'.$value."'/>";
                                        } elseif ($attrAsArray['frontend_input'] == 'file') {
                                            $_fieldValue = "<a class='wk_images' alt='file' target='_blank' href='".$this->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'pub/media/customfield/file'.$value."'>".__('Download')."</a>";
                                        } else {
                                            $_fieldValue = $value;
                                        }
                                    }
                                } ?>
                            <?php if ($_fieldValue != '' && $orderHelper->isShowInEmail($attributeData->getId())):?>
                                <tr>
                                    <td style="font-size:12px;padding:7px 9px 9px 9px;" class="label"><label><?php /* @escapeNotVerified */ echo $attributeData->getFrontendLabel() ?></label></td>
                                    <td style="font-size:12px;padding:7px 9px 9px 9px;" class="label"><label><?php /* @escapeNotVerified */ echo $_fieldValue; ?></label></td>
                                </tr>
                            <?php endif ?>

                                    
                        <?php endforeach;?>
                </table>
            </td>
        </tr>
        </tbody>
    </table>        

    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-qty">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-price">
                    <?= /* @escapeNotVerified */  __('Price'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
