<?php
    $data = $block->getModel();
    $file_signal = 0;
    $text_signal = 0;
    $code_signal = 0;
    $dependableCodeSignal = 0;
    $textarea_signal = 0;
    $dependable_textarea_signal = 0;
    $selectSignal = 0;
    $dependable_signal=0;
    $dependableSelectoptionSignal = 0;
    $dependable_allowed_extensions_signal = 0;
    $selectoption_signal = 0;
    $dependableLabel='';
    $dependableAttributeCode='';
    $dependableFrontClass = '';
    $file_extension_value='';
    $dependableFrontendInput='';
    $dependable_validation_type='';
    $dependable_requiredfield=0;
    $dependableSelectoption='';
    $selectoption='';
    $dependable_allowed_extensions='';
    if($data->getFrontendInput() == "file" || $data->getFrontendInput() == "image"){
        $file_signal = 1;
        $file_extension_value = $data->getNote();
    }
    if($data->getFrontendInput() == "text"){
        $text_signal = 1;
    }
    if($data->getAttributeId()){
        $code_signal = 1;
    }
    if($data->getFrontendInput() == "textarea"){
        $textarea_signal = 1;
    }
    if($data->getFrontendInput() == "select" || $data->getFrontendInput() == "multiselect"){
        $selectSignal = 1;
        $options = $data->getSource()->getAllOptions();
        foreach ($options as $key => $value) {
            if ($value['value'] != '')
                $selectoption .=$value['label'].',';
        }
    }
    $isRequiredArray = explode(' ', $data->getFrontendClass());
    if(in_array('dependable_field_'.$data->getAttributeCode(), $isRequiredArray)){

        $dependableData = $block->getDependableModel();
        $dependable_signal = 1;
        $dependableFrontendInput = 'dependable_'.$dependableData->getFrontendInput();
        if($dependableFrontendInput == "dependable_select" || $dependableFrontendInput == "dependable_multiselect"){
            $dependableSelectoptionSignal = 1;
        }
        if($dependableFrontendInput == "dependable_image" || $dependableFrontendInput == "dependable_file"){
            $dependable_allowed_extensions = $dependableData->getNote();
            $dependable_allowed_extensions_signal = 1;
        }
    }
?>

<script id="allowed_extension_template" type="text/x-magento-template">
    <div class="admin__field field field-allowed_extensions  required _required allowed_extensions_type_container" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-form-field-allowed_extensions">
        <label class="label admin__field-label" for="allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-input-name-label"><span><?php echo __('Allowed Extension') ?></span></label>
        <div class="admin__field-control control">
            <input id="customfields_allowed_extensions" name="allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-allowed-extensions" value="<%- data.extension %>" title="<?php echo __('Allowed Extension') ?>" type="text" class=" input-text admin__control-text required-entry _required" aria-required="true">
            <comment>eg:<%- data.allowedextension %></comment>
        </div>
    </div>
</script>
<script id="dependable_allowed_extension_template" type="text/x-magento-template">
    <div class="admin__field field field-dependable-allowed-extensions  required _required dependable_allowed_extensions_type_container" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-form-field-dependable_allowed_extensions">
        <label class="label admin__field-label" for="allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-input-name-label"><span><?php echo __('Dependable Allowed Extension') ?></span></label>
        <div class="admin__field-control control">
            <input id="customfields_allowed_extensions" name="dependable_allowed_extensions" data-ui-id="adminhtml-customfields-edit-0-form-fieldset-element-text-dependable-allowed-extensions" value="<%- data.dependExtension %>" title="<?php echo __('Dependable Allowed Extension') ?>" type="text" class=" input-text admin__control-text required-entry _required" aria-required="true">
            <comment>eg:<%- data.dependExtension %></comment>
        </div>
    </div>
</script>
<script> 
	require([
        "jquery",
        "mage/template",
        "mage/mage"
    ], function ($, mageTemplate, alert){
        var file_signal = "<?php echo $file_signal; ?>";
        var text_signal = "<?php echo $text_signal; ?>";
        var code_signal = "<?php echo $code_signal; ?>";
        var textarea_signal = "<?php echo $textarea_signal; ?>";
        var dependable_textarea_signal = "<?php echo $dependable_textarea_signal; ?>";
        var dependable_signal = "<?php echo $dependable_signal; ?>";
        var selectSignal = "<?php echo $selectSignal; ?>";
        var dependableSelectoptionSignal = "<?php echo $dependableSelectoptionSignal; ?>";
        var dependable_allowed_extensions_signal = "<?php echo $dependable_allowed_extensions_signal; ?>";
        $("#custom_attribute_tabs_main_content").find(".customfield_options").hide();
        var dependTemp = $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").parent('.entry-edit');
        var optionTemp = $("#custom_attribute_tabs_main_content").find(".customfield_options");
        $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").parent('.entry-edit').remove();
        /* if templates have some data then add template automatically */
        if (code_signal == 1){
            $("#customfields_base_fieldset").find("#customfields_attribute_code").attr('disabled','true');
            $("#customfields_base_fieldset").find("#customfields_frontend_input").attr('disabled','true');
            $("#customfields_base_fieldset").find(".field-frontend_class").show();
            $("#customfields_base_fieldset").find(".field-is_required").show();
        }
        if(dependable_signal == "1"){
            $("#custom_attribute_tabs_main_content").append(dependTemp);
            $("#custom_attribute_tabs_main_content").find("#dependable_frontend_input").attr('disabled','true');
            $("#custom_attribute_tabs_main_content").find("#dependable_attribute_code").attr('disabled','true');
            $("#customfields_base_fieldset").find(".field-frontend_class").hide();
            //$("#customfields_base_fieldset").find(".field-is_required").hide();
        }
        if(file_signal == "1"){
            $("#customfields_base_fieldset").find(".field-frontend_class").hide();
            $("#customfields_base_fieldset").find(".field-is_required").hide();
            var progressTmpl = mageTemplate('#allowed_extension_template'),
                          tmpl;
                tmpl = progressTmpl({
                        data: {
                            allowedextension:"<?php echo $file_extension_value; ?>"
                        }
                    });               
                $('.field-frontend_input').after(tmpl);
        }
        if(selectSignal == "1"){
            optionTemp.show();
            $("#customfields_base_fieldset").find("#customfields_frontend_class").attr('disabled','true');
        }
        if(textarea_signal == "1"){
            $("#customfields_base_fieldset").find("#customfields_frontend_class").attr('disabled','true');
        }
        /* END */
    	$('#customfields_frontend_input').on('change',function(){
    		$(this).parents("#customfields_base_fieldset").find(".dependable_type_container").remove();
            $(this).parents("#customfields_base_fieldset").find(".selectoption_type_container").remove();
            optionTemp.remove();
            $(this).parents("#custom_attribute_tabs_main_content").find(".allowed_extensions_type_container").remove();
            dependTemp.remove();
            if($(this).val() == 'text'){
                $("#custom_attribute_tabs_main_content").find(".customfield_options").hide();
                $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").parent('.entry-edit').remove();
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").show();
                $(this).parents("#customfields_base_fieldset").find(".field-is_required").show();
                $(this).parents("#customfields_base_fieldset").find("#customfields_frontend_class").removeAttr('disabled');
            }
            if($(this).val() == 'textarea'){
                dependTemp.remove();
                optionTemp.remove();
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").show();
                $(this).parents("#customfields_base_fieldset").find(".field-is_required").show();
                $(this).parents("#customfields_base_fieldset").find("#customfields_frontend_class").attr('disabled','true');
            }
            if($(this).val() == 'boolean'){
                dependTemp.remove();
                optionTemp.remove();
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").show();
                $(this).parents("#customfields_base_fieldset").find(".field-is_required").show();
                $(this).parents("#customfields_base_fieldset").find("#customfields_frontend_class").attr('disabled','true');
            }
            if($(this).val() == 'dependable'){
                $("#custom_attribute_tabs_main_content").append(dependTemp);
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").hide();
                $(this).parents("#customfields_base_fieldset").find(".field-is_required").hide();
                optionTemp.remove();
               /* $(this).parents("#customfields_base_fieldset").find(".field-dependable-validation-type").hide();
                $(this).parents("#customfields_base_fieldset").find(".field-dependable_required_field").hide();*/
            }
             if($(this).val() == 'date'){
                optionTemp.remove();
                $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").parent('.entry-edit').remove();
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").show();
                $(this).parents("#customfields_base_fieldset").find(".field-is_required").show();
                $(this).parents("#customfields_base_fieldset").find("#customfields_frontend_class").attr('disabled','true');
            }
            if($(this).val() == 'select' || $(this).val() == 'multiselect'){
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").show();
                $(this).parents("#customfields_base_fieldset").find(".field-is_required").show();
                $(this).parents("#customfields_base_fieldset").find("#customfields_frontend_class").attr('disabled','true');
                $("#custom_attribute_tabs_main_content").find("#customfields_base_fieldset-wrapper").append(optionTemp);
                optionTemp.show();
                $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").parent('.entry-edit').remove();
            }
            if($(this).val() == 'file' || $(this).val() == 'image'){
                var extn = 'jpg,png,gif';
                if($(this).val() == 'file') {
                    extn = 'pdf,zip,doc';
                }
                $(this).parents("#customfields_base_fieldset").find(".field-frontend_class").hide();
                //$(this).parents("#customfields_base_fieldset").find(".field-is_required").hide();
                $("#custom_attribute_tabs_main_content").find(".customfield_options").hide();
                $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").parent('.entry-edit').remove();
                var progressTmpl = mageTemplate('#allowed_extension_template'),
                          tmpl;
                tmpl = progressTmpl({
                        data: {allowedextension: extn}
                    });               
                $('.field-frontend_input').after(tmpl);
            }
        });

        /* if dependable templates have some data then add template automatically */
        if(dependable_textarea_signal == "1"){
            $("#customfields_base_fieldset").find("#customfields_dependable_validation_type").attr('disabled','true');
        }
        if(dependableSelectoptionSignal == "1"){
            $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").append(optionTemp);
            optionTemp.show();
            $("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").attr('disabled','true');
        }
        if(dependable_allowed_extensions_signal == "1"){
            var progressTmpl = mageTemplate('#dependable_allowed_extension_template'),
                          tmpl;
                tmpl = progressTmpl({
                        data: {
                            dependExtension:"<?php echo $dependable_allowed_extensions; ?>"
                        }
                    });               
                $('#dependable_inputtype').after(tmpl);
        }
        $('#custom_attribute_tabs_main_content').on('change', '#dependable_frontend_input',function(){
            $(this).parents("#custom_attribute_tabs_main_content").find(".dependable_selectoption_type_container").remove();
            $(this).parents("#custom_attribute_tabs_main_content").find(".dependable_allowed_extensions_type_container").remove();
            //$(this).parents("#customfields_base_fieldset").find(".allowed_extensions_type_container").remove();
            var dependable_value = $(this).val();
            if(dependable_value == "dependable_select" || dependable_value == "dependable_multiselect"){
                $(this).parents("#customfields_base_fieldset").find(".field-dependable_required_field").show();
                $(this).parents("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").attr('disabled','true');
                $("#custom_attribute_tabs_main_content").find("#dependable_advanced_fieldset-wrapper").append(optionTemp);
                optionTemp.show();
            }
            if(dependable_value == "dependable_file" || dependable_value == "dependable_image"){
                $(this).parents("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").attr('disabled','true');
                $(this).parents("#custom_attribute_tabs_main_content").find(".field-is_required").hide();
                var extn = 'jpg,png,gif';
                if($(this).val() == 'dependable_file') {
                    extn = 'pdf,zip,doc';
                }
                var progressTmpl = mageTemplate('#dependable_allowed_extension_template'),
                          tmpl;
                tmpl = progressTmpl({
                        data: {dependExtension:extn}
                    });               
                $('#dependable_frontend_input').parents('.field-frontend_input').after(tmpl);
                optionTemp.remove();
            }
            if($(this).val() == 'dependable_text'){
                $(this).parents("#custom_attribute_tabs_main_content").find('.dependable_advanced_fieldset-content').find(".field-is_required").show();
                $(this).parents("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").removeAttr('disabled');
                optionTemp.remove();
            }
             if($(this).val() == 'dependable_textarea'){
                $(this).parents("#custom_attribute_tabs_main_content").find('.dependable_advanced_fieldset-content').find(".field-is_required").show();
                $(this).parents("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").attr('disabled','true');
                optionTemp.remove();
            }
            if($(this).val() == 'dependable_date'){
                $(this).parents("#custom_attribute_tabs_main_content").find('.dependable_advanced_fieldset-content').find(".field-is_required").show();
                $(this).parents("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").attr('disabled','true');
                optionTemp.remove();
            }
            if($(this).val() == 'dependable_boolean'){
                $(this).parents("#custom_attribute_tabs_main_content").find('.dependable_advanced_fieldset-content').find(".field-is_required").show();
                $(this).parents("#custom_attribute_tabs_main_content").find("#dependable_frontend_class").attr('disabled','true');
                optionTemp.remove();
            }
        });
    });

</script>