<?php
/**
 * Cibilianpayout template for separate item
 *
 */

/**
 * @var $this Cibilia\Cibilianpayout\Block\View
 * @see Cibilia\Cibilianpayout\Block\View
 */
?>
<?php $_cibilianpayoutItem = $this->getCibilianpayout(); ?>
    <div class="cibilianpayout_item_subtitle">
        <?php echo $this->formatDate($_cibilianpayoutItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_cibilianpayoutItem->getAuthor()) ?>
    </div>

<div class="cibilianpayout_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_cibilianpayoutItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_cibilianpayoutItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="cibilianpayout_item_content"><?php echo $_cibilianpayoutItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>