<?php //$this->helper('Cibilia\Cibilians\Helper\Customer')->redirectIfNotLoggedIn();?>
<?php

$vid = $this->getRequest()->getParam('id');
$objVendor = $block->getVendor($vid);
$subDomian   =   str_replace('http://','.',$block->getBaseUrl());
$helper =   $this->helper('StageBit\CustomCode\Helper\Data');
?>
<?php if ($objVendor && $objVendor->getId()) { ?>
    <form class="form-address-edit" method="POST"
          enctype="multipart/form-data"
          action="<?php echo $this->getUrl('idproofs/index/vendorpost', array('id' => $vid)); ?>"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */
                    echo __('Step 1') ?></span></legend>
            <br>
            <div class="field name required">
                <label class="label" for="vendor_name"><span><?php echo __('Company Name') ?></span></label>
                <div class="control">
                    <input name="vendor_name" id="vendor_name" title="<?php echo __('Company name') ?>"
                           value="<?php echo $objVendor->getVendorName(); ?>" class="input-text" type="text"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field name required">
                <label class="label"
                       for="owner_name"><span><?php echo __('Name and Surname of Owner/Responsible') ?></span></label>
                <div class="control">
                    <input name="owner_name" id="owner_name"
                           value="<?php echo $objVendor->getOwnerName(); ?>"
                           title="<?php echo __('Name and Surname of Owner/Responsible') ?>" value="" class="input-text"
                           type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <?php $getVendorRole = $block->getVendorRole(); ?>
            <?php if (count($getVendorRole) > 0) { ?>
                <div class="field name required">
                    <label class="label" for="your_role"><span><?php echo __('Your role') ?></span></label>
                    <div class="control">
                        <select id="your_role" name="your_role"
                                class="required-entry ">
                            <?php foreach ($getVendorRole as $key => $value) { ?>
                                <option <?php if ($value['value'] == $objVendor->getYourRole()) {
                                    echo 'selected="selected"';
                                } ?> value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            <?php } ?>

            <div class="field name required">
                <label class="label"
                       for="company_address"><span><?php echo __('Company Registered Address') ?></span></label>
                <div class="control">
                    <input name="company_address" id="company_address"
                           title="<?php echo __('Company Registered Address') ?>"
                           value="<?php echo $objVendor->getCompanyAddress(); ?>" class="input-text" type="text"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?php echo __('Email Address') ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?php echo __('Email') ?>"
                           value="<?php echo $objVendor->getEmail(); ?>" class="input-text" disabled="disabled"
                           type="email"
                           data-validate="{required:true}"/>
                </div>
            </div>

            <?php $getCompanyEmployee = $block->getCompanyEmployee(); ?>
            <div class="field name required">
                <label class="label"
                       for="company_employee"><span><?php echo __('Question 1: How many people work in the company you wish to sign up?') ?></span></label>
                <div class="control">
                    <select id="company_employee" name="company_employee"
                            class="  required-entry validate-select">
                        <?php foreach ($getCompanyEmployee as $key => $value) { ?>
                            <option <?php if ($value['value'] == $objVendor->getCompanyEmployee()) {
                                echo 'selected="selected"';
                            } ?> value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <?php $getCompanyType = $block->getCompanyType(); ?>
            <div class="field name required">
                <label class="label"
                       for="company_type"><span><?php echo __('Question 2: Is your company part of a group of companies?') ?></span></label>
                <div class="control">
                    <select id="company_type" name="company_type"
                            class=" required-entry validate-select">
                        <?php foreach ($getCompanyType as $key => $value) { ?>
                            <option <?php if ($value['value'] == $objVendor->getCompanyType()) {
                                echo 'selected="selected"';
                            } ?> value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </fieldset>
        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */
                    echo __('Step 2') ?></span></legend>
            <br>
            <?php $productCategories = $block->productCategories(); ?>
            <div class="field name required">
                <label class="label"
                       for="product_categories"><span><?php echo __('In which categories your products fit in?') ?></span></label>
                <div class="control">
                    <select id="product_categories" name="product_categories[]"
                            class="validate-select required-entry" multiple="multiple" required>
                        <?php foreach ($productCategories as $key => $value) { ?>
                            <?php if ($value['label'] == 'Pick relevant categories:') {
                                continue;
                            } else { ?>
                                <option <?php if (in_array($value['value'], $objVendor->getProductCategories())) {
                                    echo 'selected="selected"';
                                } ?> value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <?php $productSellPlace = $block->productSellPlace(); ?>
            <?php if (count($productSellPlace) > 0) { ?>
                <div class="field required">
                    <label for="product_sell_place[]"
                           class="label"><span><?php echo __('Where do you currently sell your products?') ?></span></label>
                    <div class="control">
                        <select class="validate-select"
                                title="<?php echo __('Where do you currently sell your products?') ?>"
                                name="product_sell_place[]" id="product_sell_place" multiple="multiple" required>
                            <?php foreach ($productSellPlace as $key => $value) { ?>
                                <?php if ($value['label'] == 'Please select') {
                                    continue;
                                } else { ?>
                                    <option <?php if (in_array($value['value'], $objVendor->getProductSellPlace())) {
                                        echo 'selected="selected"';
                                    } ?> value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            <?php } ?>

            <div class="field name required">
                <label class="label" for="product_sell_place_other"><span><?php echo __('other') ?></span></label>
                <div class="control">
                    <input name="product_sell_place_other" id="product_sell_place_other"
                           value="<?php echo $objVendor->getProductSellPlaceOther(); ?>"
                           title="<?php echo __('other') ?>" value="" class="input-text" type="text"
                           data-validate="{required:false}" required/>
                </div>
            </div>
            <div class="field name required">
                <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?php echo __('Phone Number') ?>"
                           value="<?php echo $objVendor->getTelephone(); ?>"
                           class="input-text validate-digits required-entry" minlength="10" maxlength="12" type="text"
                           data-validate="{required:false}" required/>
                </div>
            </div>

            <?php $bestTimeTocall = $block->bestTimeToCall(); ?>
            <?php if (count($bestTimeTocall) > 0) { ?>
                <div class="field required">
                    <label for="best_time_to_call"
                           class="label"><span><?php echo __('When is the best time to call you ') ?></span></label>
                    <div class="control">
                        <select class="validate-select" title="<?php echo __('When is the best time to call you') ?>"
                                name="best_time_to_call" id="best_time_to_call" required>
                            <?php foreach ($bestTimeTocall as $key => $value) { ?>
                                <option <?php if ($value['value'] == $objVendor->getBestTimeToCall()) {
                                    echo 'selected="selected"';
                                } ?> value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            <?php } ?>
            <div class="field name required">
                <label class="label" for="vat_number"><span><?php echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input name="vat_number" id="vat_number" title="<?php echo __('VAT Number') ?>"
                           value="<?php echo $objVendor->getVatNumber(); ?>"
                           class="input-text" type="text" required/>
                </div>
            </div>
            <div class="field name required">
                <label class="label" for="foundation_year"><span><?php echo __('Year of foundation') ?></span></label>
                <div class="control">
                    <input name="foundation_year" id="foundation_year" title="<?php echo __('Year of foundation') ?>"
                           value="<?php echo $objVendor->getFoundationYear(); ?>" class="input-text" type="number"
                           max="2017" required/>
                </div>
            </div>
            <div class="field name">
                <label class="label" for="vendor_fbpage"><span><?php echo __('Facebook Page') ?></span></label>
                <div class="control">
                    <input name="vendor_fbpage" id="vendor_fbpage" title="<?php echo __('Facebook Page') ?>"
                           value="<?php echo $objVendor->getVendorFbpage(); ?>" class="input-text" type="text"
                           data-validate="{required:false}"/>
                </div>
            </div>
            <div class="field">
                <label class="label" for="website"><span><?php echo __('Website') ?></span></label>
                <div class="control">
                    <input name="vendor_website" id="vendor_website" type="text"
                           value="<?php echo $objVendor->getVendorWebsite(); ?>" data-validate="{required:false}"/>
                </div>
            </div>
            <div class="field name">
                <label class="label"
                       for="company_linkedin"><span><?php echo __('Company LinkedIn page ') ?></span></label>
                <div class="control">
                    <input name="company_linkedin" id="company_linkedin"
                           title="<?php echo __('Company LinkedIn page ') ?>"
                           value="<?php echo $objVendor->getCompanyLinkedin(); ?>" class="input-text" type="text"/>
                </div>
            </div>
            <div class="field name">
                <label class="label" for="company_twitter"><span><?php echo __('Company twitter') ?></span></label>
                <div class="control">
                    <input name="company_twitter" id="company_twitter" title="<?php echo __('Company twitter') ?>"
                           value="<?php echo $objVendor->getCompanyTwitter(); ?>" class="input-text" type="text"/>
                </div>
            </div>
            <div class="field name">
                <label class="label" for="url_key"><span><?php echo __('Preferred subdomain name') ?></span></label>
                <div class="control">
                    <input name="url_key" id="url_key" title="<?php echo __('Preferred subdomain name') ?>"
                           value="<?php echo $objVendor->getUrlKey(); ?>"
                           class="input-text" type="text"/>
                    <strong><?php echo substr($subDomian, 0, -1); ?></strong>
                </div>
            </div>

            <div class="field required">
                <label class="label" for="logo"><span><?php echo __('Logo Image'); ?></span></label>
                <div class="control">
                    <?php if($objVendor->getLogo()) { ?>
                        <div class="img-block">
                            <a href="<?php echo $helper->getMediaUrl().$objVendor->getLogo(); ?>" target="_blank">
                                <img src="<?php echo $helper->getMediaUrl().$objVendor->getLogo(); ?>" alt="logo" />
                            </a>
                        </div>
                        <div class="block-input">
                    <?php } ?>
                            <input id="logo" name="logo" value="" type="file" class="input-file" />
                            <div class="clearfix"></div>
                            <span>(supported file: svg, png, jpg, jpeg)</span>
                    <?php if($objVendor->getLogo()) { ?> </div> <?php } ?>
                </div>
            </div>
            <div class="field">
                <label class="label" for="company_photos"><span><?php echo __('Photo to the label of the product you wish to add'); ?> </span></label>
                <div class="control">
                    <?php if($objVendor->getCompanyPhotos()) { ?>
                        <div class="img-block">
                            <a href="<?php echo $helper->getMediaUrl().$objVendor->getCompanyPhotos(); ?>" target="_blank">
                                <img src="<?php echo $helper->getMediaUrl().$objVendor->getCompanyPhotos(); ?>" alt="company photo" />
                            </a>
                        </div>
                    <div class="block-input">
                    <?php } ?>
                        <input id="company_photos" name="company_photos" value="" type="file" class=" input-file" />
                        <div class="clearfix"></div>
                        <span>(supported file: jpg, jpeg)</span>
                    <?php if($objVendor->getCompanyPhotos()) { ?> </div> <?php } ?>
                </div>
            </div>

            <!-- <?php
            /*            $arrVendorcat = $block->getVendorcat();
                        */ ?>
            <?php /*if (count($arrVendorcat) > 0) { */ ?>
                <?php /*$arrVendorCats = explode(',', $objVendor->getVendorCategories()); */ ?>
                <div class="field">
                    <label for="vendor_categories"
                           class="label"><span><?php /*echo __('Choose the categories which the company you are referring.') */ ?></span></label>
                    <div class="control">
                        <select style="height: 150px;background:none;" data-validate="{required:true}"
                                class="validate-select multi-select"
                                title="<?php /*echo __('Choose the categories which the company you are referring') */ ?>"
                                name="vendor_categories[]" id="vendor_categories" aria-required="true"
                                multiple="multiple">
                            <?php /*foreach ($arrVendorcat as $key => $value) { */ ?>
                                <option <?php /*echo (in_array($value['value'], $arrVendorCats)) ? 'selected="selected"' : ""; */ ?>
                                        value="<?php /*echo $value['value']; */ ?>"><?php /*echo $value['label']; */ ?></option>
                            <?php /*} */ ?>
                        </select>
                    </div>
                </div>
            --><?php /*} */ ?>
            <!--<div class="field required">
            <label for="vendor_about" class="label"><span><?php /*echo __('What do you know about this company ?') */ ?></span></label>
            <div class="control">
                <textarea style="height: 150px;background:none;" data-validate="{required:true}" class="textarea" title="<?php /*echo __('What do you know about this company ?') */ ?>"  name="vendor_about" id="vendor_about" aria-required="true"><?php /*echo $objVendor->getVendorAbout();*/ ?></textarea>
            </div>
        </div>
        <div class="field required">
            <label for="vendor_letter" class="label"><span><?php /*echo __('Write a short motivation letter that will be sent along with your application form to the contact person you are about to contact with this form.') */ ?></span></label>
            <div class="control">
                <textarea  style="height: 150px;background:none;" data-validate="{required:true}" class="textarea" title="<?php /*echo __('Write a short motivation letter that will be sent along with your application form to the contact person you are about to contact with this form.') */ ?>" name="vendor_letter"  id="vendor_letter" aria-required="true"><?php /*echo $objVendor->getVendorLetter();*/ ?></textarea>
            </div>
        </div>
        <div class="field required">
            <label for="vendor_represent" class="label"><span><?php /*echo __('How would you present this company publicly ?') */ ?></span></label>
            <div class="control">
                <textarea  style="height: 150px;background:none;" data-validate="{required:true}" class="textarea" title="<?php /*echo __('How would you present this company publicly ?') */ ?>"  name="vendor_represent" id="vendor_represent" aria-required="true"><?php /*echo $objVendor->getVendorRepresent();*/ ?></textarea>
            </div>
        </div>-->
        </fieldset>
        <?php
        //$arrVendorName = explode(" ", $objVendor->getvendorAttn(), 2);
        //  $strVendorFname = $arrVendorName[0];
        //  $strVendorLname = $arrVendorName[1];
        ?>
        <!-- <fieldset class="fieldset">
            <legend class="legend"><span><?php /*/* @escapeNotVerified */
        //     echo __('Contact Information') */?></span></legend>
            <br>
            <div class="field required">
                <label class="label"
                       for="vendor_fname"><span><?php /*echo __('Contact Person First Name') */ ?></span></label>
                <div class="control">
                    <input name="vendor_fname" id="vendor_fname" title="<?php /*echo __('Contact Person First Name') */ ?>"
                           value="<?php /*echo $strVendorFname; */ ?>" class="input-text" type="text"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"
                       for="vendor_lname"><span><?php /*echo __('Contact Person Last Name') */ ?></span></label>
                <div class="control">
                    <input name="vendor_lname" id="vendor_lname" title="<?php /*echo __('Contact Person Last Name') */ ?>"
                           value="<?php /*echo $strVendorLname; */ ?>" class="input-text" type="text"
                           data-validate="{required:true}"/>
                </div>
            </div>


        </fieldset>-->
        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */
                    echo __('Login Information') ?></span></legend>
            <br>
            <div class="field required">
                <label class="label" for="vendor_userid"><span><?php echo __('User Id') ?></span></label>
                <div class="control">
                    <input disabled="disabled" name="vendor_userid" id="vendor_userid"
                           title="<?php echo __('User Id') ?>" value="<?php echo $objVendor->getEmail(); ?>"
                           class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field required">
                <label class="label" for="password"><span><?php echo __('Password') ?></span></label>
                <div class="control">
                    <input name="password" id="password" title="<?php echo __('Password') ?>" value=""
                           class="input-text" type="password" data-validate="{required:true}"/>
                </div>
            </div>
        </fieldset>
        <?php $arrVendortype = $block->getVendortype(); ?>
        <fieldset class="fieldset" style="display: none">
            <legend class="legend"><span><?php /* @escapeNotVerified */
                    echo __('Vendor Type Selection') ?></span></legend>
            <br>
            <div class="field name required">
                <label class="label" for="vendor_type"><span><?php echo __('Select your type') ?></span></label>
                <div class="control">
                    <?php if (count($arrVendortype) > 0) { ?>
                        <?php foreach ($arrVendortype as $key => $value) { ?>
                            <?php if ($value['value'] == 0 || $value['value'] == 2) {
                                continue;
                            } ?>
                            <input type="radio"
                                   data-validate="{required:true}" <?php echo ($value['value'] == 1) ? 'checked="checked"' : ''; ?>
                                   name="vendor_type"
                                   value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?><br>
                        <?php } ?>

                    <?php } ?>
                </div>
            </div>
        </fieldset>
        <div style="clear:both;">&nbsp;</div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */
                echo __('Save Info') ?>">
                    <span><?php /* @escapeNotVerified */
                        echo __('Save Info') ?></span>
                </button>
            </div>
        </div>
        <style type="text/css">
            .form-address-edit .fieldset:nth-child(3), .form-address-edit .fieldset:nth-child(4) {
                float: right;
                clear: none;
            }
        </style>
    </form>
<script type="text/javascript">
    require(["jquery", "prototype", "varien/form", "bootstrapMin", "bootstrapMultiselect"], function($) {
        $('#product_categories').multiselect({
            includeSelectAllOption: true,
            maxHeight: 150,
        });

        $('#product_sell_place').multiselect({
            includeSelectAllOption: true,
            maxHeight: 150,
        });
    });
</script>
<?php } else { ?>
    <h4><?php echo __('No Vendor Found') ?></h4>
<?php } ?>
