<?php $this->helper('Cibilia\Cibilians\Helper\Customer')->redirectIfNotLoggedIn();?>
<form class="form-address-edit" method="POST" action="<?php echo $this->getUrl('umicrosite/vendor/registerpost'); ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'> 
 <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('General Information') ?></span></legend><br>

         <div class="field name required">
            <label class="label" for="vendor_name"><span><?php echo __('Company Name') ?></span></label>
            <div class="control">
                <input name="vendor_name" id="vendor_name" title="<?php echo __('Company name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required">
            <label class="label" for="website"><span><?php echo __('Website') ?></span></label>
            <div class="control">
                <input name="website" id="website" type="text" data-validate="{required:true}"/>
            </div>
        </div>
         <div class="field required">
            <label class="label" for="vendor_attn"><span><?php echo __('Contact Person') ?></span></label>
            <div class="control">
                <input name="vendor_attn" id="vendor_attn" title="<?php echo __('Contact Person') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br>
       
        <div class="field required">
            <label class="label" for="telephone"><span><?php echo __('Mobile') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php echo __('Mobile') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php echo __('Email') ?>" value="" class="input-text" type="email" data-validate="{required:true}"/>
                <input name="password" value="vendor123" class="input-text" type="hidden"/>
                <input name="password_confirm" value="vendor123" class="input-text" type="hidden"/>
				<input name="udmember[membership]" value="1" class="input-text" type="hidden"/>
                <input name="carrier_code" value="fedex" class="input-text" type="hidden"/>
                <input name="url_key" value="test" class="input-text" type="hidden"/>
                <input name="street1" value="Your address" class="input-text" type="hidden"/>
                <input name="city" value="City name" class="input-text" type="hidden"/>
                <input name="zip" value="121212" class="input-text" type="hidden"/>
                <input name="country_id" value="In" class="input-text" type="hidden"/>
            </div>
        </div>
      
        
    </fieldset>
	 <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Product details') ?></span></legend><br>

         <div class="field name required">
            <label class="label" for="product_name"><span><?php echo __('Product Name') ?></span></label>
            <div class="control">
                <input name="product_name" id="product_name" title="<?php echo __('Product name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
         <div class="field required">
            <label class="label" for="price"><span><?php echo __('Price') ?></span></label>
            <div class="control">
                <input name="price" id="price" title="<?php echo __('Price') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required">
            <label class="label" for="product_description"><span><?php echo __('Product description') ?></span></label>
            <div class="control">
                <input name="product_description" id="product_description" type="text" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
	 <fieldset class="fieldset">
             
        <div class="field required">
            <label class="label" for="product_sku"><span><?php echo __('Product SKU') ?></span></label>
            <div class="control">
                <input name="product_sku" id="product_sku" type="text" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field required">
            <label class="label" for="image"><span><?php echo __('Product image') ?></span></label>
            <div class="control">
                <input name="image" id="image" title="<?php echo __('Product image') ?>" value="" class="input-text" type="file" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
	
</form>