<?php
/**
 * Commissions template for separate item
 *
 */

/**
 * @var $this Cibilia\Commissions\Block\View
 * @see Cibilia\Commissions\Block\View
 */
?>
<?php $_commissionsItem = $this->getCommissions(); ?>
    <div class="commissions_item_subtitle">
        <?php echo $this->formatDate($_commissionsItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_commissionsItem->getAuthor()) ?>
    </div>

<div class="commissions_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_commissionsItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_commissionsItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="commissions_item_content"><?php echo $_commissionsItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>