<ul id="svg-icons" class="header links">
    <li class="ai-icon">
        <a href="<?php echo $block->getUrl('udropship/vendor'); ?>">
            <svg version="1.1" id="bi-globe" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
                <path fill="none" d="M22.5,50A27.5,27.5 0,1,1 77.5,50A27.5,27.5 0,1,1 22.5,50" style="stroke-dasharray: 173, 213; stroke-dashoffset: 0;"></path>
                <path fill="none" d="M34.8,50A15.2,27.2 0,1,1 65.2,50A15.2,27.2 0,1,1 34.8,50" style="stroke-dasharray: 136, 176; stroke-dashoffset: 0;"></path>
                <path fill="none" d="M50,22.5L50,77.5" style="stroke-dasharray: 55, 95; stroke-dashoffset: 0;"></path>
                <path fill="none" d="M22.8,50A27.2,15.2 0,1,1 77.2,50A27.2,15.2 0,1,1 22.8,50" style="stroke-dasharray: 136, 176; stroke-dashoffset: 0;"></path>
                <path fill="none" d="M22.5,50L77.5,50" style="stroke-dasharray: 55, 95; stroke-dashoffset: 0;"></path>
            </svg><?php echo __('Il mio account'); ?>
        </a>
    </li>
    <li class="authorization-link ai-icon" data-label="or">
        <a href="<?php echo $block->getUrl('udropship/vendor'); ?>">
            <svg version="1.1" id="si-lock" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
                <path d="M31.709,42.761L31.709,74.581L49.854,74.581L50.146,74.581L68.291,74.581L68.291,42.761Z" style="stroke-dasharray: 137, 177; stroke-dashoffset: 0;"></path>
                <path d="M31.709,42.761c0,0,0.742-17.342,18.291-17.342s18.291,17.342,18.291,17.342" style="stroke-dasharray: 57, 97; stroke-dashoffset: 0;"></path>
                <path d="M46,62.722A4,4 0,1,1 54,62.722A4,4 0,1,1 46,62.722" style="stroke-dasharray: 26, 66; stroke-dashoffset: 0;"></path>
            </svg><?php echo __('Entra'); ?>
        </a>
    </li>
</ul>